repository:
    path: github.com/cloudflare/unsee
build:
    binaries:
        - name: unsee
          path: .
    flags: -a -tags netgo
    ldflags: |
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}

tarball:
    files:
        - docs/example.yaml
        - LICENSE

crossbuild:
    platforms:
# The build is failing for 386 architecture
# It's removed here until we fix it
        - linux/amd64
        - darwin/amd64
        - windows/amd64
        - freebsd/amd64
        - openbsd/amd64
        - netbsd/amd64
        - dragonfly/amd64
        - linux/arm64
        - linux/ppc64
